### ISSUE TITLE
Gorilla Player 0.9.1.2 does not work

### ISSUE THREAD

**Issue by adrianknight89** [UXDivers/Gorilla-Player-Support#141]
Installed Gorilla Player 0.9.1.2. 

Unfortunately, neither the release app from the app store nor the VS solution works. Auto-discover does not work. I even tried manually adding the server. The server seems to be running on the PC but the device can't find it.

Tested this on iOS 9.

**Comment by LeoHere** [comment]
Can you provide me more details about your environment? Windows/Mac? XS/VS? Real device/emulator?

Please confirm that the server is running by visiting ```http://localhost:9014``` from your desktop machine browser. There you will see the network interfaces the server is listening at. Try visiting ```http://<server ip>:9014``` from the device's browser to be sure you can reach the server from your device.

**Comment by jpbrocca** [comment]
@adrianknight89, can you provide more info about your environment ?
Thanks a lot!

**Comment by aamir-amwar** [comment]
Hi, I am also facing this problem. I have gorilla player 0.9.1.2 version install on my mac and 0.9.0.8 version of app install from app store on my iPhone. The gorilla player app discovered the server correctly and it also shows the server that is running on my mac. The problem is that when i select server from app and click "Connect" button...  Connect button immediately shows "Disconnect" title and then again to previous state. Means, it didn't connect to the server.

**Comment by LeoHere** [comment]
@aamir-amwar, can you send me the logs generated in your desktop machine? Take a look at [this](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-Player-logs-location) document to find out where are the logs. I would need gorillaHost.log and gorillaPlayer.log. Please email me the logs to l r o d r i g u e z at u x d i v e r s . c o m

**Comment by tlhintoq** [comment]
Windows10, Visual Studio 2015, Looks like the service can't start.  When I try to got the address in browser the response is:

HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.
Detailed Error Information:
Module	   IIS Web Core
Notification	   BeginRequest
Handler	   Not yet determined
Error Code	   0x800700b7
Config Error	   Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'IsapiModule'
Config File	   \\?\C:\inetpub\temp\apppools\DefaultAppPool\DefaultAppPool.config

So... Is the port address conflicting with another service?

**Comment by LeoHere** [comment]
@tlhintoq please check the connectivity troubleshooting guide [here](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Troubleshoouting-Connectivity).

By default Gorilla is listening at [http://localhost:9014](http://localhost:9014). I guess that the error your are getting is from your local IIS.
