### ISSUE TITLE
Use with Xamarin Studio beta(Xaml preview)

### ISSUE THREAD

**Issue by AresDev** [UXDivers/Gorilla-Player-Support#160]
I've installed the beta version of Xamarin Studio beta, with the now included feature, and Gorilla Player was able to connect to server in iOS emulator and everything seemed to be ok but when opening Xaml files, nothing was being show on Gorilla Player. 

I don't know if I have to do some configuration or what? 

Then I installed the stable version and everything was working fine again.

**Comment by jpbrocca** [comment]
Hi @AresDev,
We only give support for stable versions of Xamarin Studio -no Beta versions are supported-.

Regards,
JP

**Comment by AresDev** [comment]
Ok, now is the stable version and still not working.

**Comment by LeoHere** [comment]
@AresDev, with the XS 6.1 update the Follow Me feature stops working. You can still manually move between XAML files using the "Stick to this XAML". This issue seems to be only affecting Mac.

There is an updated version of the adding that fixes the issue. Please find it attached.
[UXDivers.Artina.Player.Addins.Gorilla Player_0.9.2.3.mpack.zip](https://github.com/UXDivers/Gorilla-Player-Support/files/489581/UXDivers.Artina.Player.Addins.Gorilla.Player_0.9.2.3.mpack.zip)

You will need to unzip the mpack file and install it from Xamarin Studio>Add-ins>Install from file

Please, if it fix your problem Close the issue.

**Comment by AresDev** [comment]
Thank you! now it's working!
