### ISSUE TITLE
Gorilla Player is connected but nothing previewed

### ISSUE THREAD

**Issue by jebeyl** [UXDivers/Gorilla-Player-Support#179]
I am using Visual Studio 2015 on Windows 7. Although I have installed the mobile app on my android device and it connects correctly, on the gorilla player window it shows only the following: "Currently Previewing:{name of the xaml file}" and "File location:{the location of the xaml file}".

Please check the attached screenshot.

What am I doing wrong?

![screenshot](https://cloud.githubusercontent.com/assets/17849151/20135655/89ecf63a-a679-11e6-9798-b34381e15897.png)

**Comment by jpbrocca** [comment]
Hi @jebeyl,
Did you check the Troubleshooting Connectivity Guide?
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Troubleshoouting-Connectivity

Best,
JP

**Comment by jebeyl** [comment]
Hi, thanks for answering. I am getting the preview in my device now but in Gorilla Player Status Window it still shows the aforementioned text. Sorry if I got something wrong, I just thought that I would see my xaml preview in a Window on my desktop too. Did I misunderstand it?

**Comment by jpbrocca** [comment]
Hi @jabeyl,
The main benefit of using Gorilla Player is that will be able to preview directly on devices (emulators and real devices both). You can also preview all platforms at the same time, which means you could see an iPhone and an Android tablet simultaneously. This is a huge timesaver and gives you the most accurate preview because you can get the real UI rendered on an specific platform version.

Being all that said, we will be adding a panel on visual/xamarin studio so you could preview also on the IDE.

Best
JP

**Comment by jebeyl** [comment]
Thanks, you are awesome.

**Comment by jpbrocca** [comment]
I am closing this issue now since you are being able to.preview.
Feel free to re open if neccesary.

Best,
JP
