### ISSUE TITLE
Support for VS2017 RC

### ISSUE THREAD

**Issue by ShiroYacha** [UXDivers/Gorilla-Player-Support#184]
Hello,

Is there any plan on releasing a VS2017 compatible plugin?

Thanks,
Min

**Comment by LeoHere** [comment]
We will have a VS2017 plugin for sure. How many of you did already jump to VS2017? Is it stable enough?

**Comment by ShiroYacha** [comment]
Haven't tested all the new features but as for now the RC is actually quite stable to use (community version).

**Comment by TonyHenrique** [comment]
Release a Visual Studio 2017 plugin.

**Comment by nnddnn** [comment]
Yes, please make it for 2017RC!

**Comment by DeRas** [comment]
I'm also interested in a VS 2017 plugin :)

**Comment by Cristian126** [comment]
A VS 2017 plugin will be great!

**Comment by Mr-Pearce** [comment]
Since Visual Studio 2017 will be released in about a week  [Link](https://launch.visualstudio.com/?utm_source=ms&utm_medium=banner&utm_content=vscom&utm_campaign=vs2017rtm)
A VS 2017 Plugin would be really great.

**Comment by weitzhandler** [comment]
Would love to see VS 2017 support too.
Thank you!

**Comment by attrib75** [comment]
Now that VS2017 is out, does Gorilla Player work for it?

**Comment by LeoHere** [comment]
@attrib75 @weitzhandler @Mr-Pearce @Cristian126 @DeRas @nnddnn @TonyHenrique @ShiroYacha attached you can find the VSIX for VS2017. Please let me know if you found any issue.

[UXDivers.Artina.Player.VSAddin.vsix.zip](https://github.com/UXDivers/Gorilla-Player-Support/files/847243/UXDivers.Artina.Player.VSAddin.vsix.zip)

Needed to zip it since Github don't allow uploading .vsix files directly. Just unzip it an execute the VSIX.

Enjoy and sorry for the long wait.

**Comment by DeRas** [comment]
I got it working. Holy crap its good :) Thanks @LeoHere !

**Comment by attrib75** [comment]
Works great!  Thanks!

**Comment by weitzhandler** [comment]
@LeoHere
Is this going to be added to the VS extension gallery?

**Comment by LeoHere** [comment]
@weitzhandler, Yes we will.

**Comment by mdowais** [comment]
I have created a blank PCL Project, and i get an error
"Error occurred while setting Gorilla Target XAML. File Name MainPage.xaml
(Internal Error) Check Logs<..>"

{"level":"info","message":"Gorilla Server: info: Adding solution (from VS - 15.0): PATH_TO_PROJ\\visual studio 2017\\Projects\\App5\\App5.sln \r\n","timestamp":"2017-05-19T14:10:08.791Z"}

{"level":"info","message":"Gorilla Server: info: Setting Target: MainPage.xaml (PATH_TO_PROJ\\visual studio 2017\\Projects\\App5\\App5\\App5\\App5.csproj) requested from VS (15.0)\r\n","timestamp":"2017-05-19T14:10:09.816Z"}

{"level":"info","message":"Gorilla Server: info: Solution not found\r\n","timestamp":"2017-05-19T14:10:09.816Z"}

The Sample app works fine, but when i create a new project, this happens.. 

is there anything needed to do with vcproj of the project?? a taught!!

**Comment by LeoHere** [comment]
@mdowais, no you don't need to do anything special, it should work.

Is there any special character in the **PATH_TO_PROJ** portion of the path? If that is the case, can you try coping the solution to a different location to avoid that characters, and test it from there?

If that fixes the issue please sent me an email to l r o d r i g u e z at uxdivers.com and I will share with you the last dev version of Gorilla where that issue is fixed.

**Comment by weitzhandler** [comment]
@LeoHere is it in the ex. gallery?

**Comment by mdowais** [comment]
i dono what happened but everything is fine now.. i guess there was a problem with the location path i guess... everything works fine now.. thaanks for the reply!!

**Comment by huynq9** [comment]
works like a charm!
