### ISSUE TITLE
Unhandled Exception: UXDivers.Artina.Shared.LicenseException: Error reading license. occurred

### ISSUE THREAD

**Issue by wiltwitt** [UXDivers/Gorilla-Player-Support#196]
I created a starter kit and copied a GrialLicense to my existing app but I am getting  "Unhandled Exception: UXDivers.Artina.Shared.LicenseException: Error reading license. occurred" error.  It has same project name, package name, and all.   Android app builds but fails at UXDivers.Artina.Shared.GrialKit.Init(this, "myapp.GrialLicense");  

Is there a list I can find to check off?  thanks (FYI. starter app builds and runs ok)

**Comment by LeoHere** [comment]
Please ensure that:
- ```GrialLicense``` has build Action Embedded Resource and is included at the root of your Android project
- Invoke ```GrialKit.Init``` passing the name of the embedded resource, which is ```<Default Namespace of the Container Project>.GrialLicense``` (assuming that the license file is called ```GrialLicense```). So for example, if your default namespace is ```my.cool.app```, in Android you should invoke ``` UXDivers.Artina.Shared.GrialKit.Init(this, "my.cool.app.GrialLicense");```

**Comment by walysonmax** [comment]
I renewed the license and is throwing this exception

**Comment by LeoHere** [comment]
@walysonmax can you please elaborate a bit more on how you end up with this error? Did you double check that the ```GrialLicense``` is correctly setup and named (see my previous post)?  Also please check the [License Troubleshooting](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-troubleshooting-license-issues) in the documentation.

**Comment by walysonmax** [comment]
was changed build Action, thats ok, thanks

**Comment by DeanWilliamMills** [comment]
I am getting the exact same error.

GrialLicense file is under root Android project
The GrialLicense is set to Embedded Resource

I am calling it like this:
`GrialKit.Init(this, "Platform.Droid.GrialLicense");`
where Platform is my project namespace.

Any other solutions?

**Comment by LeoHere** [comment]
@DeanWilliamMills if you are working with Grial 3 please take a look at this [Troubleshooting Guide](http://docs.grialkit.com/troubleshooting.html#troubleshooting-license-issues). If you are in Grial 2 read this [Troubleshooting Guide](https://docs.grialkit.com/v2/#grial-uikit-overview-grial-first-run-troubleshooting-license-issues).

I'm closing this issue since it is a Grial UI Kit issue posted in the Gorilla Forum. If you can't solve it please open a new issue in the [Grial UI Kit forum](https://github.com/UXDivers/Grial-UI-Kit-Support/issues).
