### ISSUE TITLE
Error occurred while setting Gorilla Target XAML

### ISSUE THREAD

**Issue by kellelein** [UXDivers/Gorilla-Player-Support#226]
I have just installed the new Gorilla Player ver. 1.0 for Xamarin Forms, but can't get it to work in a "real world solution". If I create a new solution in Visual Studio and play with different controls, the Player works just fine.

When I try to view a XAML file I get the folowing error message in Visual Studio 2015

"Error occurred while setting Gorilla Target XAML. File Views\MainPagePhone.xaml (Errors occured while registering its solution)."

And then

"Error occurred while setting Gorilla Target XAML. File Views\MainPagePhone.xaml (Internal error, please see logs to get more information)."

I have looked in the log file, but can't see what's going wrong

**Comment by DelcoigneYves** [comment]
Are you targetting .NET Standard in your real world solution?

I have the exact same issue when targetting .NET standard 1.4.
Also when creating a "normal" .NET Standard project (instead of choosing to create a Xamarin class library and then converting to .NET standard), this issue occurs.

Logs are telling me this:
`{"processingIssue":true,"issueType":"error","position":null,"area":"Gral","scope":"Sol","error":{"name":"TypeError","message":"Cannot call method 'toUpperCase' of null","stack":"TypeError: Cannot call method 'toUpperCase' of null\n    at Object.utils.compareItemProjectItemsAbsolutePath (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\Utils.js.jx:348:58)\n    at Object.getSharedProject (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:158:35)\n    at Object.analyzeProjectDependencies (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:233:50)\n    at Object.analyzeAllProjectsRelations (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:178:30)\n    at Object.<anonymous> (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:336:23)\n    at Object.<anonymous> (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:476:21)\n    at Object.tryCatcher (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\util.js.jx:25:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\promise.js.jx:509:31)\n    at Promise._settlePromiseAt (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\promise.js.jx:583:18)\n    at Async._drainQueue (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:127:12)\n    at Async._drainQueues (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:132:10)\n    at Async.drainQueues (C:\\Users\\yves_\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:14:14)\n    at process._tickCallback (node.js:803:1)"},"contextInstanceId":8,"targetId":0,"sampleDataId":0,"level":"error","message":"Xaml processing error Summary:\"Error parsing the solution\"; Message:\"Error occurred while parsing the solution (Cannot call method 'toUpperCase' of null)\"","timestamp":"2017-07-20T14:46:33.800Z"}
{"contextInstanceId":8,"targetId":0,"sampleDataId":0,"level":"info","message":"Notifing issues found (errors: 1, warnings: 2)","timestamp":"2017-07-20T14:46:33.801Z"}`

Seems like the solution name can't be found when a file in a .NET standard project is chosen?

**Comment by vitorlans** [comment]
I also. I'm having the same trouble, I was able to use after remove ios and android from solution, but it's impossible to use this way.

from gorillaHost.log this is the only error I had.
`{"level":"error","message":"[Server] Xaml processing error Summary:\"Error parsing the solution\"; Message:\"Error occurred while parsing the solution (**Cannot call method 'toUpperCase' of null**)\" processingIssue=true, issueType=error, position=null, area=Gral, scope=Sol, name=TypeError, message=Cannot call method 'toUpperCase' of null, stack=TypeError: Cannot call method 'toUpperCase' of null\n    at Object.utils.compareItemProjectItemsAbsolutePath (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\Utils.js.jx:348:58)\n    at Object.getSharedProject (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:158:35)\n    at Object.analyzeProjectDependencies (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:233:50)\n    at Object.analyzeAllProjectsRelations (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:178:30)\n    at Object.<anonymous> (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:336:23)\n    at Object.<anonymous> (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\SolutionParser.js.jx:476:21)\n    at Object.tryCatcher (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\util.js.jx:25:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\promise.js.jx:509:31)\n    at Promise._settlePromiseAt (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\promise.js.jx:583:18)\n    at Async._drainQueue (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:127:12)\n    at Async._drainQueues (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:132:10)\n    at Async.drainQueues (C:\\Users\\vitor.santos\\AppData\\Local\\Programs\\Gorilla Player\\1.0.0\\resources\\node_modules\\bluebird\\js\\main\\async.js.jx:14:14)\n    at process._tickCallback (node.js:803:1), contextInstanceId=1, targetId=0, sampleDataId=0\r\n","timestamp":"2017-07-18T20:54:02.139Z"}
`

**Comment by kellelein** [comment]
_Are you targetting .NET Standard in your real world solution?_ 

It's all standard, I'm targetting .NET Framework 4.5

**Comment by LeoHere** [comment]
@kellelein, can you send me the logs to l r o d r i g u e z at uxdivers.com? (you can access them from the context menu in the system try)

@DelcoigneYves & @vitorlans, .NET Standard projects are not supported yet.

**Comment by kellelein** [comment]
Mail send LeoHere :-)

**Comment by peter-gabriel** [comment]
@LeoHere, are there any plans to support .NET Standard projects?

**Comment by LeoHere** [comment]
@peter-gabriel yes, but we don't have a date, yet.

**Comment by beylkhanovdamir** [comment]
@LeoHere 

> "message":"Xaml processing error Summary:\"Error analyzing project files.\"; Message:\"Error reading D:\\Projects\\my-app\\**\\*.xaml during file classification (ENOENT, open 'D:\\Projects\\my-app\\**\\*.xaml').\""

**Comment by kayjoekahmann** [comment]
Is there any update to this issue yet?

**Comment by ebicoglu** [comment]
Is there any update for .net standard?

**Comment by ddobrev** [comment]
Hello, I have a .NET Standard project for Xamarin.Forms, in fact, PCL seems not to work any more. So I have no choice - does Gorilla already support .NET Standard?

**Comment by LeoHere** [comment]
Hi, Gorilla 1.2 with .NET Standard support has been released. Please check [this blog post](https://grialkit.com/2017/12/gorilla-player-1-2-net-standard-support/) for more information. Closing the issue. If you find out any issue please open a new one.

**Comment by zgramana** [comment]
I have the same problem and narrowed it down to the following test case (below). Both are functionally equivalent at runtime, but are probably troublesome for the Player logic.
## Nominal Case
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="TestApp.Shared.TestPage">
    <ContentPage.Content>
        <StackLayout><Label Text="Hello!" FontSize="48" /></StackLayout>
    </ContentPage.Content>
</ContentPage>
```
```csharp
using System;
using System.Collections.Generic;

using Xamarin.Forms;

namespace TestApp.Shared
{
    public partial class TestPage : ContentPage
    {
        public TestPage()
        {
            InitializeComponent();
        }
    }
}
```
## Error Case
```xml
<?xml version="1.0" encoding="UTF-8"?>
<local:TestPageXaml xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TestApp.Shared"
             x:Class="TestApp.Shared.TestPage">
    <local:TestPageXaml.Content>
        <StackLayout><Label Text="Hello!!" FontSize="48" /></StackLayout>
    </local:TestPageXaml.Content>
</local:TestPageXaml>
```
```csharp
using System;
using System.Collections.Generic;

using Xamarin.Forms;

namespace TestApp.Shared
{
    public partial class TestPage : TestPageXaml
    {
        public TestPage()
        {
            InitializeComponent();
        }
    }

    public partial class TestPageXaml : ContentPage
    {
        
    }
}
```
