### ISSUE TITLE
Build fails for Full version of Gorilla Enabled Android version of my App

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Gorilla-Player-Support#295]
Hello Community,

I am facing compilation error (see attached) while compiling Full version of Gorilla Enabled Android version of my App. It is an as-is code for my App downloaded from my Grial Admin site for the first time.

[Environment details - GrialKit 2.7 | VS 15.7.4 | Win 10 Pro 10.0.17134 Build 17134 ]

Your input to address this issue will be appreciated.

Thank you.

![fullgrialkitproject-gorillaenabled-androidbuilderror1](https://user-images.githubusercontent.com/26844611/42415412-f998e7d4-8212-11e8-832c-5b04eca481a1.JPG)

![fullgrialkitproject-gorillaenabled-androidbuilderror2](https://user-images.githubusercontent.com/26844611/42415413-fc449b5e-8212-11e8-98d2-7c027f848121.JPG)

**Comment by LeoHere** [comment]
Hi @IoTFier!

This issues happens because the namespace used by your project ends with `Android` which collides with the root `Android` namespace defined by the Android SDK. When the compiler tries to typecheck code like this:

~~~
#if GORILLA
public override bool OnKeyUp (Android.Views.Keycode keyCode, Android.Views.KeyEvent e)  
~~~

It tries to find `Views.Keycode` in your `Android` namespace, not the `Android` root namespace defined by the Android SDK, thus it ends up failing.

You have two alternatives to fix this:
1. Change the namespace of you Android project from `XXXX.Android` to `XXXX.Droid` or anything else that make sense for you to avoid collisions. 
2. Add the `global::` to any reference of a type that references the Android SDK `Android` namespace. In the case of the keyup it would be something like this:

~~~
#if GORILLA
public override bool OnKeyUp (global::Android.Views.Keycode keyCode, global::Android.Views.KeyEvent e)  
{  
    if ((keyCode == global::Android.Views.Keycode.F1 || 
          keyCode == global::Android.Views.Keycode.Menu || 
          keyCode == global::Android.Views.Keycode.VolumeUp || 
          keyCode == global::Android.Views.Keycode.VolumeDown || 
          keyCode == global::Android.Views.Keycode.VolumeMute) && 
          UXDivers.Gorilla.Coordinator.Instance != null) 
        {  
		UXDivers.Gorilla.ActionManager.ShowMenu();
		return true; 
	} 

	return base.OnKeyUp (keyCode, e); 
}
...
~~~

If possible, I would recommend you to following the first approach, so you avoid having to deal with this disambiguation in the future.

We will fix this in the Admin to avoid this problem.

**Comment by IoTFier** [comment]
Hi @LeoHere , thank you for your guidance. 
I am opting for 2nd alternative. I prefer to have .Android in my namespace and having namespace cover folder names containing each file / resource items as applicable.
I am compiling with the suggested changes; but the build process is taking forever at the step where it is trying to sign the .jar file using apksigner.jar  I have been waiting for at least 15-20 mins.

**Comment by IoTFier** [comment]
Hi @LeoHere, I am able to build and deploy full version of my Gorilla Enabled app to Android device.
I have opted for 2nd alternative. Hopefully, in the next release Grial team can address this issue in the Admin.

Thank you for your help.
