### ISSUE TITLE
Can't Connect version 1.5.0.0

### ISSUE THREAD

**Issue by cgomezm** [UXDivers/Gorilla-Player-Support#314]
I'm gettig error: incompatible server version 1.5.0.0 when trying to connect my device. Any suggestions?
![whatsapp image 2018-11-08 at 18 52 39 1](https://user-images.githubusercontent.com/24781329/48234507-e2cd5e00-e387-11e8-9cf4-4449cd1a12cb.jpeg)
![whatsapp image 2018-11-08 at 18 52 39 2](https://user-images.githubusercontent.com/24781329/48234509-e2cd5e00-e387-11e8-8a17-8196b0f4ba85.jpeg)
![whatsapp image 2018-11-08 at 18 52 39 3](https://user-images.githubusercontent.com/24781329/48234510-e2cd5e00-e387-11e8-9af1-fdc5742bd01f.jpeg)

**Comment by leo-mck** [comment]
Hey @cgomezm I am having the same problem, was you able to resolve this issue?

**Comment by cgomezm** [comment]
Yes! You have to:
- install gorilla player on your PC
- on install extras select examples and install
- in new examples folder open gorilla player solution and deploy to your device.
That's it!

Note: the play store and app store app are both out of date, that's why you get incompatible version error

**Comment by leo-mck** [comment]
It worked, thanks! :)

**Comment by LeoHere** [comment]
@leo-mck @cgomezm deploying that solution would allow to preview only XAML that includes stuff from Xamarin Forms core. You will not be able to preview your controls, custom renderers, etc.

We removed those apps from the store mainly because they were a big source of confusion. 

In order to preview your custom stuff you should use Gorilla SDK. I would recommend that you try the new AutoConfig feature released in Gorilla 1.5. This [blog post](https://blog.xamarin.com/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/) gives a good presentation of the feature. Here are the [release notes](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Release-Notes-Gorilla-Player-1.5) for Gorilla 1.5.

Hope it helps.
