### ISSUE TITLE
Multiple devices preview simultaneously 

### ISSUE THREAD

**Issue by LeoJHarris** [UXDivers/Gorilla-Player-Support#339]
Hi is it still possible to do multiple devices preview? 

Below video which is a bit old shows it was possible using the Gorilla player but that app is no longer available on the stores (https://play.google.com/store/apps/details?id=uxdivers.gorilla - dead link). Was this functionality dropped? If some one could enlighten me how to get multiple devices previewing simultaneously that'd be much appreciated!

The video I found was: https://www.youtube.com/watch?v=zBs2oTZ3XzM which shows it was possible to to preview multiple devices simultaneously.

**Comment by LeoHere** [comment]
@LeoJHarris yes you can preview in multiple devices at the same time. In order to do that you need to setup Gorilla SDK on your project and deploy it to each device you want to preview with. Once you do that, just connect all the devices to the server and start previewing. 

Follow the steps described in [this](https://blog.xamarin.com/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/) blog post to setup Gorilla SDK.
