### ISSUE TITLE
Gorilla Player does not work in Parallels environment

### ISSUE THREAD

**Issue by adersonrangel** [UXDivers/Gorilla-Player-Support#73]
I am working with Parallels with emulators but none of them allows me to run the Gorilla. It is never connected in Adroid or iOS, android emulator is Xamarin default Player which bring this ip 10.71.34.101. Could you help me

**Comment by pmace** [comment]
Me too! Win10 Pro/VS 2015 on a Mac in Parallels 11

**Comment by adersonrangel** [comment]
Yes, I have the same configuration Win10 Pro/VS 2015 on a Mac in Parallels 11

**Comment by LeoHere** [comment]
Thanks for your feedback.

The good news is that I have exactly the same environment and it is working fine with the VS Android emulator and the iOS emulator (running on the host Mac). So let's figure out what is the problem here.

First of all, my environment:

* Mac OSX El Capitan
  * iOS Simulator 9.3
  * Gorilla Player iOS App
* Parallels 11 - Windows 10 Pro (network configuration = Shared)
  * Visual Studio 2015 - Community Edition
  * Gorilla Player desktop app
  * VS Android Emulator
     * Gorilla Player Android app

Where did you installed Gorilla? You should install it within your Windows VM.

In my case once I open Gorilla desktop app and deployed the Android version to the emulator, autodiscovery works as expected and I can easly preview.

In the case of the iOS emulator, autodiscovery will not work out of the box. You should use "Manual Setup" specifing the ip:port (e.g. 10.71.34.101:9014 assuming that is the address of your vm). In order to support auto discovery for the iOS simulator or connecting an actual physical device, you will need to setup a couple of port fordwarding rules (see [this](https://github.com/UXDivers/Gorilla-Player-Support/issues/63) for more details)

**Comment by pmace** [comment]
So, A few things to note:

**You Need to Spend TIme on the Installation and Getting Started Docs.
**  You seem to be under the impression the Expectation-setting and setup steps match and are clear--they are not.

- The installer never 'appears' to finish.  Oh, it says it got 2 of 3--no XS in the VM Win10--so that fails. And that makes literal sense. But then it just sits there with the two options: Install, or Not Now.  Pressing Install just keeps repeating the 2 of 3 success. If you hit the windows 'x' and close the window thinking you are done, you are in fact hosed.  Nothing in the docs makes any sense if you do that.  Only when you hit Not Now do you make any progress.  Not good.  **You need a modal box to indicate Next->** when there has been success, or "Try again?" if not

- You keep talking about the desktop app, but that's not true. It's a service that runs with an icon in the service tray.  You need to say that in the Getting Started section.

-  Getting Started also needs to call out the mandatory deployment of player to simulators steps...as it is, the expectation set by screenshots is this all just works...which it does not.

Both IOS and Android-running-in-VM simulators required manual setup 

- **After All This**, The Gorilla icon now appears overlaid on xaml files inside VS, but that is it.  Nothing else.  Not encouraging for a visualization tool and not consistent with the expectations set in the docs and on the website.

I expected to see emulation inside VS--or an emulation window popup.  I did not expect Player+Simulator was a requirement, or the clever but abnormal need to load the Xamarin player project and deploy.

And the Player not only needs to be installed on the simulators, it needs to be manually set running.

Now, finally, the IOS sim reflects the XAML layout for the Sample...But It fails with my xaml code with an "Error setting Gorilla Target..." message.  Probably a Forms 2.x issue?

And I still can't get the Android and IOS sims to run simultaneously--you seem to be using websockets, so why this is is a mystery.

Paul Mace
