### ISSUE TITLE
No title bar iOS [v. 0.8.3]

### ISSUE THREAD

**Issue by pablos91** [UXDivers/Gorilla-Player-Support#76]
There's no title bar even though I didn't hide it purposely. Maybe if I would add some toolbar items it will show up ?

Anyway it looks far different from what it looks like on emulator.

**Comment by james-lavery** [comment]
Doesn't this depend on the implementation you're intending the Page to be displayed in? Gorilla doesn't know whether a title bar is needed or not.

I'm being a bit pedantic here I know. However, I agree that the ability to at least 'mock' a title bar would be useful - otherwise on iOS the view in Gorilla is shifted right up to the top of the screen.

**Comment by jpbrocca** [comment]
Hi @pablos91, please take a look at #31.
This is fixed on 0.9.0.1.

And here is the documentation to handle the NavigationPage preview:
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Previewing-within-a-Navigation-Page

Regards and thanks!
JP
