### ISSUE TITLE
Toolbar Items do not display (v0.8.3.0)

### ISSUE THREAD

**Issue by ntrhieu89** [UXDivers/Gorilla-Player-Support#87]
Toolbar Items do not display in Gorilla Player.

Example:

 ```
 <ContentPage.ToolbarItems>
    <ToolbarItem Name="Edit"></ToolbarItem>
    <ToolbarItem Name="Delete"></ToolbarItem> 
    <ToolbarItem Name="Group"></ToolbarItem>
  </ContentPage.ToolbarItems>
```

**Comment by LeoHere** [comment]
Hi @ntrhieu89, this issue is fixed in the last release. Please see this [issue](https://github.com/UXDivers/Gorilla-Player-Support/issues/31) for more information. I'm closing this issue for now. If you have any problem please report it in [this](https://github.com/UXDivers/Gorilla-Player-Support/issues/31) issue.
