### ISSUE TITLE
Cannot install addin for Xamarin Studio

### ISSUE THREAD

**Issue by kentcb** [UXDivers/Gorilla-Player-Support#99]
Hi,

I'm trying to install on a Mac. I have the latest Xamarin beta channel installed. The UI gives me the message "Oh snap! Gorilla Player Addin for Xamarin Studio installation failed!". The entire contents of _gorillaHost.log_ is:

```
{"level":"info","message":"Starting Gorilla App...","timestamp":"2016-05-23T05:03:57.439Z"}
{"level":"info","message":"Configured server with name Gorilla on Kents-MBP, stored in configuration file /Users/kent/.gorilla/config.json","timestamp":"2016-05-23T05:03:57.728Z"}
{"level":"info","message":"Terms and conditions accepted.","timestamp":"2016-05-23T05:04:02.641Z"}
{"level":"error","message":"MDTool exitcode 255","timestamp":"2016-05-23T05:04:31.362Z"}
{"level":"error","message":"MDTool exitcode 255","timestamp":"2016-05-23T12:29:51.119Z"}
```

Any suggestions?

**Comment by jpbrocca** [comment]
Hi,
Are you using xamarin studio 6?
If so, then please take a look at the following issue and close this one:

https://github.com/UXDivers/Gorilla-Player-Support/issues/46
El may. 23, 2016 9:33 AM, "Kent Boogaart" <notifications@github.com>
escribió:

Hi,

I'm trying to install on a Mac. I have the latest Xamarin beta channel
installed. The UI gives me the message "Oh snap! Gorilla Player Addin for
Xamarin Studio installation failed!". The entire contents of
*gorillaHost.log* is:

{"level":"info","message":"Starting Gorilla
App...","timestamp":"2016-05-23T05:03:57.439Z"}
{"level":"info","message":"Configured server with name Gorilla on
Kents-MBP, stored in configuration file
/Users/kent/.gorilla/config.json","timestamp":"2016-05-23T05:03:57.728Z"}
{"level":"info","message":"Terms and conditions
accepted.","timestamp":"2016-05-23T05:04:02.641Z"}
{"level":"error","message":"MDTool exitcode
255","timestamp":"2016-05-23T05:04:31.362Z"}
{"level":"error","message":"MDTool exitcode
255","timestamp":"2016-05-23T12:29:51.119Z"}

Any suggestions?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/UXDivers/Gorilla-Player-Support/issues/99>
